name: Install local R package on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dont-check" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        r-version: ['4.3.1']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0      
          
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          
      # Installing system dependencies for tcltk and other potential requirements
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev tcl8.6-dev tk8.6-dev xvfb libcurl4-openssl-dev
        
      - name: Install R dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install rcmdcheck
        run: |
          Rscript -e 'install.packages("rcmdcheck")'

      - name: Start Xvfb
        run: |
          Xvfb :99 &
          export DISPLAY=:99.0

      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual --as-cran", error_on = "never", build_args = "--no-build-vignettes")
        shell: Rscript {0}
        timeout-minutes: 10
