name: Install local R package on Windows

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.3.1']

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      
      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual --as-cran", error_on = "never", build_args = "--no-build-vignettes")
        shell: Rscript {0}
        timeout-minutes: 10
