name: MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.3.1']

    steps:
      - uses: actions/checkout@v3
      
      # Install XQuartz for tcltk support
      - name: Install XQuartz
        run: |
          brew install --cask xquartz
          brew list --cask | grep xquartz

      - name: List Applications
        run: ls /Applications
              
      - name: Check XQuartz installation
        run: ls /Applications/Utilities/XQuartz.app

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Set DISPLAY for XQuartz
        run: |
          echo "DISPLAY=:0.0" >> $GITHUB_ENV

      - name: Set non-interactive graphics device
        run: |
          echo "options(device = 'pdf')" >> ~/.Rprofile

      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual --as-cran", error_on = "never", build_args = "--no-build-vignettes")
        shell: Rscript {0}
        timeout-minutes: 10
